services:
 selenium:
  image: selenium/standalone-chrome
  build:
   context: .
   shm_size: '2gb'
  ports:
   - 4444:4444
 railwiredashboard:
  image: varun8104/railwiredashboard
  ports:
   - 8501:8501
