# Your workflow name.
name: Deploy to heroku.


on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Compose-checker
        uses: isbang/compose-action@v1.4.1


      - name: Build, Push and Release a Docker container to Heroku. 
        uses: gonuit/heroku-docker-deploy@v1.3.3 
        with:
         
          email: ${{ secrets.HEROKU_EMAIL }}
          
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

          dockerfile_directory: ./

          compose-file: "docker-compose.yml"

          services: |
            selenium
            railwiredashboard
          
          docker_options: "--no-cache"

          process_type: web
          
